name = "Oipd"
uuid = "d5722cbd-5612-498c-a56c-8c01aca498af"
authors = ["Gene Wicaksono"]
version = "1.0.0-DEV"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"


[compat]
CondaPkg = "0.2.33"
DataFrames = "1.8.1"
Dates = "1.11.0"
Distributions = "0.25.122"
Plots = "1.41.3"
PythonCall = "0.9.31"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
